### PR TITLE
django tutorial

### PR DESCRIPTION
**Pull request by whoburg**
work in progress, not ready for review.

I'm running through the Django tutorial at https://docs.djangoproject.com/en/2.1/intro/tutorial01/ line by line and pushing to this branch.

### CODE REVIEW

**Comment by whoburg** [comment]
tutorial complete (through part 7, https://docs.djangoproject.com/en/2.1/intro/tutorial07/), and pushed to this branch. I'm going to start adapting to our use case now. TBD whether it makes sense to start with the end point of the tutorial or start fresh. I'll do that work on a different branch.

**Comment by whoburg** [comment]
@matthewdominick, I plan to close this PR without merging (it was just me getting Django practice). Sound ok?

**Comment by matthewdominick** [comment]
So . . . I should definitely not merge this pull request after reading it.

**Comment by whoburg** [comment]
closing without merging.

**Pull request closed without merging**
